---
driver:
  name: docker
  hostname: gnocchi.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: gnocchi
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - gnocchi
  pillars:
    top.sls:
      base:
        "*":
          - gnocchi

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:
  - name: default
  #  provisioner:
  #    pillars-from-files:
  #      gnocchi.sls: tests/pillar/default.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
